version: 2.1

orbs:
  python: circleci/python@1.3.3

workflows:
  test-build-push-image:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest 
