version: 2.1

orbs:
  python: circleci/python@1.3.3
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  test-build-push-image:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: unittest 
      - aws-ecr/build-and-push-image:
          repo: devops-bookstore-api
          tag: '1.$CIRCLE_BUILD_NUM'
          requires:
            - "python/test"
